ankietka/ankieter/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls import url


app_name = 'ankieter'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^profil/$', views.ProfilView.as_view(), name='profil'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^create/$', views.dodaj_ankiete, name="create"),
#    url(r'^create2/$', views.dodaj_grupe, name="create2"),
#    url(r'^create3/$', views.dodaj_pytanie, name="create3"),
#    url(r'^create4/$', views.dodaj_wybor, name="create4"),
    url(r'^glownawyniki$', views.Glownawyniki.as_view(), name="glownawyniki"),
    path('<int:pk>/', views.SzczegolyView.as_view(), name='szczegoly'),
    path('<int:pk>/wyniki/', views.WynikiView.as_view(), name='wyniki'),
    path('<int:pytanie_id>/glos/', views.glos, name='glos'),
    path('<int:pk>/grupy/', views.grupy, name='grupy'),
    path('<int:pk>/pytania/', views.pytania, name='pytania'),
    path('<int:pk>/wybory/', views.wybory, name='wybory'),
    path('<int:pk>/create2/', views.dodaj_grupe, name="create2"),
    path('<int:pk>/create3/', views.dodaj_pytanie, name="create3"),
    path('<int:pk>/create4/', views.dodaj_wybor, name="create4"),
]

ankietka/ankietka/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('ankieter/', include('ankieter.urls', namespace='ankieter')),

]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ankietka/ankieter/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User



class Ankieta(models.Model):
    nazwa_ankiety = models.CharField(max_length=30, default=None)
    autor = models.ForeignKey(User, default=None, on_delete=None)
    def __str__(self):
        return self.nazwa_ankiety
    class Meta:
        verbose_name = 'Ankieta'
        verbose_name_plural = 'Ankiety'



class Grupa(models.Model):
    ankieta = models.ForeignKey(Ankieta, on_delete=models.CASCADE, default=None)
    nazwa_grupy = models.CharField(max_length=30, default=None)
    def __str__(self):
        return self.nazwa_grupy
    class Meta:
        verbose_name = 'Grupa'
        verbose_name_plural = 'Grupy'



class Pytanie(models.Model):
    ankieta = models.ForeignKey(Ankieta, on_delete=models.CASCADE, default=None, blank=True)
    grupa = models.ForeignKey(Grupa, on_delete=models.CASCADE, default=None, blank=True)
    pytanie_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    pytanie_plik = models.ImageField(default=None, blank=True, null=True)
    autor = models.ForeignKey(User, default=None, on_delete=None)
    def __str__(self):
        return self.pytanie_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    class Meta:
        verbose_name = 'Pytanie'
        verbose_name_plural = 'Pytania'



class Wybor(models.Model):
    pytanie = models.ForeignKey(Pytanie, on_delete=models.CASCADE)
    wybor_text = models.CharField(max_length=200, blank=True)
    votes = models.IntegerField(default=0)
    plik = models.ImageField(default=None, blank=True)
    def __str__(self):
        return self.wybor_text
    class Meta:
        verbose_name = 'Wybor'
        verbose_name_plural = 'Wybory'

ankietka/ankieter/forms.py
from django import forms
from .models import Pytanie, Wybor, Grupa, Ankieta



class StworzPytanie(forms.ModelForm):
    class Meta:
        model = Pytanie
        fields = ['pytanie_text', 'pytanie_plik', 'ankieta',]
        exclude = ['autor', 'pub_date']




class StworzWybor(forms.ModelForm):
    class Meta:
        model = Wybor
        fields = '__all__'
        exclude = ['votes','pytanie', ]



class StworzAnkiete(forms.ModelForm):
    class Meta:
        model = Ankieta
        fields = ['nazwa_ankiety',]


class StworzGrupe(forms.ModelForm):
    class Meta:
        model = Grupa
        fields = ['nazwa_grupy',]

ankietka/ankieter/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import Pytanie, Wybor, Ankieta, Grupa
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from . import forms
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'ankieter/index.html'
    context_object_name = 'lista_ostatnich_ankiet'

    def get_queryset(self):
        return Ankieta.objects.order_by('id') [:15]

class SzczegolyView(generic.DetailView):
    model = Ankieta
    template_name = 'ankieter/szczegoly.html'

class WynikiView(generic.DetailView):
    model = Ankieta
    template_name = 'ankieter/wyniki.html'



def glos(request, pytanie_id,):
    pytanie = Pytanie.objects.get(pk=pytanie_id)
    ankieta = pytanie.ankieta
    if request.method == 'POST':
        wybor_id = request.POST['wybor']
        wybor = Wybor.objects.get(pk=wybor_id)
        wybor.votes += 1
        wybor.save()
        return HttpResponseRedirect(reverse('ankieter:szczegoly', args=(ankieta.id,)))
    return render(request, 'ankieter/szczegoly.html', {'pytanie': pytanie})



def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('ankieter:profil')
    else:
        form = UserCreationForm()
    return render(request,'ankieter/signup.html', {'form':form})



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('ankieter:profil')
    else:
        form = AuthenticationForm()
    return render(request, 'ankieter/login.html', {'form': form})



def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect('ankieter:index')



class Glownawyniki(generic.ListView):
    template_name = 'ankieter/glownawyniki.html'
    context_object_name = 'lista_ostatnich_ankiet'

    def get_queryset(self):
        return Ankieta.objects.order_by('id') [:15]


class ProfilView(generic.ListView):
    template_name = 'ankieter/profil.html'
    context_object_name = 'lista_ostatnich_ankiet'

    def get_queryset(self):
        return Ankieta.objects.order_by('id')



def grupy(request, pk):
    ankieta = Ankieta.objects.get(id = pk)
    context = {
    'grupy': Grupa.objects.filter(ankieta = ankieta),
    'ankieta': ankieta

    }
    return render(request, 'ankieter/grupy.html', context)



def pytania(request, pk):
    grupa = Grupa.objects.get(id = pk)
    context = {
    'pytania': Pytanie.objects.filter(grupa = grupa),
    'grupa': grupa
    }
    return render(request, 'ankieter/pytania.html', context)


def wybory(request, pk):
    pytanie = Pytanie.objects.get(id = pk)
    context = {
    'wybory': Wybor.objects.filter(pytanie = pytanie),
    'pytanie': pytanie
    }
    return render(request, 'ankieter/wybory.html', context)





@login_required(login_url="/ankieter/login/")
def dodaj_ankiete(request):
    if request.method == 'POST':
        form = forms.StworzAnkiete(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.autor = request.user
            instance.save()
            return redirect('ankieter:profil')
    else:
        form = forms.StworzAnkiete()
    return render(request, 'ankieter/create.html', {'form':form})



@login_required(login_url="/ankieter/login/")
def dodaj_grupe(request, pk):
    ankieta = Ankieta.objects.get(id = pk)
    if request.method == 'POST':
        form2 = forms.StworzGrupe(request.POST, request.FILES)
        if form2.is_valid():
            instance2 = form2.save(commit=False)
            instance2.ankieta = ankieta
            instance2.save()
            return redirect('ankieter:profil')
    else:
        form2 = forms.StworzGrupe()
    return render(request, 'ankieter/create2.html', {'form2':form2, 'ankieta':ankieta})

@login_required(login_url="/ankieter/login/")
def dodaj_pytanie(request, pk):
    grupa = Grupa.objects.get(id = pk)
#    ankieta = Ankieta
    if request.method == 'POST':
        form3 = forms.StworzPytanie(request.POST, request.FILES)
        if form3.is_valid():
            instance3 = form3.save(commit=False)
            instance3.pub_date = timezone.now()
            instance3.autor = request.user
            instance3.grupa = grupa
#            instance3.ankieta = Ankieta
            instance3.save()
            return redirect('ankieter:profil')
    else:
        form3 = forms.StworzPytanie()
    return render(request, 'ankieter/create3.html', {'form3':form3, 'grupa':grupa})

@login_required(login_url="/ankieter/login/")
def dodaj_wybor(request, pk):
    pytanie = Pytanie.objects.get(id = pk)
    if request.method =='POST':
        form4 = forms.StworzWybor(request.POST, request.FILES)
        if form4.is_valid():
            instance4 = form4.save(commit=False)
            instance4.pytanie = pytanie
            instance4.votes = 0
            instance4.save()
            return redirect('ankieter:profil')
    else:
        form4 = forms.StworzWybor()
    return render(request, 'ankieter/create4.html', {'form4':form4, 'pytanie':pytanie})































pass

ankietka/ankieter/templates/ankieter/create.html
{% extends 'podstawa.html'%}

{% block content %}
<h1> Lista Ankiet </h1>
{% if lista_ostatnich_ankiet %}
    <ul>
    {% for ankieta in lista_ostatnich_ankiet %}
        <li><a href="{% url 'ankieter:wyniki' ankieta.id %}">{{ ankieta.nazwa_ankiety }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nie ma dostepnych ankiet.</p>
{% endif %}

  <div class="create">
    <h2>Stworz sb ankietke</h2>
    <br></br>
    <form class="site-form" action="{% url 'ankieter:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Stworz">
    </form>

  </div>
{% endblock %}

ankietka/ankieter/templates/ankieter/create2.html
{% extends 'podstawa.html'%}

{% block content %}


  <div class="create">
    <h2>Stworz sb grupke</h2>
    <br></br>
    <form class="site-form" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form2 }}
      <input type="submit" value="Stworz">
    </form>

  </div>
{% endblock %}

ankietka/ankieter/templates/ankieter/create3.html
{% extends 'podstawa.html'%}

{% block content %}


  <div class="create">
    <h2>Stworz sb pytanko</h2>
    <br></br>
    <form class="site-form" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form3 }}
      <input type="submit" value="Stworz">
    </form>
  </div>
{% endblock %}

ankietka/ankieter/templates/ankieter/create4.html
{% extends 'podstawa.html'%}

{% block content %}


  <div class="create">
    <h2>Stworz sb odpowiedz</h2>
    <br></br>
    <form class="site-form" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form4 }}
      <input type="submit" value="Stworz">
    </form>

  </div>
{% endblock %}

ankietka/ankieter/templates/ankieter/glownawyniki.html
{% extends 'podstawa.html' %}

{% block content %}

    <h1> Wyniki Ankiet znajdziesz na tej stronie !  </h1>

    {% if lista_ostatnich_ankiet %}
        <ul>
        {% for ankieta in lista_ostatnich_ankiet %}
            <li><a href="{% url 'ankieter:wyniki' ankieta.id %}">{{ ankieta.nazwa_ankiety }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Nie ma dostepnych ankiet.</p>
{% endif %}

{% endblock %}

ankietka/ankieter/templates/ankieter/grupy.html
{% extends 'podstawa.html' %}

{% block content %}
<p> Grupy Ankiety {{ ankieta.nazwa_ankiety }} </p>
<ul>
  {% for g in grupy %}
    <li><a href="{% url 'ankieter:pytania' g.id %}">{{ g.nazwa_grupy }} {{g.pk}}</a></li>
  {% endfor %}
</ul>
<a href="{% url  'ankieter:create2' ankieta.id %}"> + Grupa </a>

{% endblock %}

ankietka/ankieter/templates/ankieter/index.html
{% extends 'podstawa.html' %}

{% block content %}

    <h1> Glowna Lista Ankiet </h1>
{% if lista_ostatnich_ankiet %}
    <ul>
    {% for ankieta in lista_ostatnich_ankiet %}
        <li><a href="{% url 'ankieter:szczegoly' ankieta.id %}">{{ ankieta.nazwa_ankiety }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nie ma dostepnych ankiet.</p>
{% endif %}

{% endblock %}

ankietka/ankieter/templates/ankieter/login.html
{% extends 'podstawa.html'%}

{% block content %}
  {% if request.GET.next %}
  <h2>Aby przejsc dalej musisz sie zalogowac!</h2>
  <br></br>
  {% else %}
  <h2>LOGUJ SIE !</h2>
  <br></br>
{% endif %}
  <form class="site-form" action="{% url 'ankieter:login'%}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% endif %}

    <input type="submit" value="Zaloguj">

  </form>
{% endblock %}

ankietka/ankieter/templates/ankieter/profil.html
{% extends 'podstawa.html' %}

{% block content %}
<h1> Witaj {% if user.is_authenticated %}{{ user }} {% endif %} !</h1>
<h2>Twoje Ankiety:</h2>
{% if lista_ostatnich_ankiet %}
<ul>
  {% for ankieta in lista_ostatnich_ankiet %}
      {% if user == ankieta.autor %}
        <li><a href="{% url 'ankieter:grupy' ankieta.id %}">{{ ankieta.nazwa_ankiety }} {{ankieta.pk}}</a></li>
      {% endif %}
  {% endfor %}
</ul>
{% else %}
    <p>Nie ma dostepnych ankiet.</p>
{% endif %}

<a href="{% url 'ankieter:create' %}"> + Ankieta </a>


{% endblock %}

ankietka/ankieter/templates/ankieter/pytania.html
{% extends 'podstawa.html' %}

{% block content %}
<p> Pytania Grupy: "{{ grupa.nazwa_grupy }}" </p>
<ul>
  {% for p in pytania %}
  {% if p.pytanie_plik.url is not None %}
  <img src="{{ p.pytanie_plik.url }}"  width="15%" height="15%"/>
  {% endif %}
    <li><a href="{% url 'ankieter:wybory' p.id %}">{{ p.pytanie_text }}</a></li>
  {% endfor %}
</ul>
<a href="{% url 'ankieter:create3' grupa.id %}"> + Pytanie </a>

{% endblock %}

ankietka/ankieter/templates/ankieter/signup.html
{% extends 'podstawa.html'%}

{% block content %}
  <h1>SIEMA REJESTRUJ SIE</h1>

  <form class="site-form" action="/ankieter/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Zarejestruj">

  </form>
{% endblock %}

ankietka/ankieter/templates/ankieter/szczegoly.html
{% extends 'podstawa.html' %}

{% block content %}

  <p> {{  ankieta.nazwa_ankiety }} </p>
<ul>
{% for grupa in ankieta.grupa_set.all %}
  <li> {{ grupa.nazwa_grupy }} </li>

<ul>
{% for pytanie in grupa.pytanie_set.all %}
<p>Pytanie {% if pytanie.autor.is_superuser %}administratora {% else %}uzytkownika {% endif %}{{pytanie.autor}} :</p>

<p>{{ pytanie.pytanie_text }}</p>
{% if pytanie.pytanie_plik.url is not None %}
<img src="{{ pytanie.pytanie_plik.url }}"  width="15%" height="15%"/>
{% endif %}
<form action="{% url 'ankieter:glos' pytanie.id %}" method="post">
{% csrf_token %}
{% for wybor in pytanie.wybor_set.all %}
    <input type="radio" name="wybor" id="wybor{{ forloop.counter }}" value="{{ wybor.id }}" />
    <label for="wybor{{ forloop.counter }}">{{ wybor.wybor_text}}{% if wybor.plik.url is not None %}<img src="{{ wybor.plik.url }}"  />{% endif %}</label><br />
{% endfor %}
<input type="submit" value="Glosuj" />
</form>
{% endfor %}
</ul>

{% endfor %}
</ul>


{% endblock %}

ankietka/ankieter/templates/ankieter/wybory.html
{% extends 'podstawa.html' %}

{% block content %}
<p> Wybory Pytania: "{{ pytanie.pytanie_text }}" </p>
<ul>
  {% for w in wybory %}
  <li>  {{ w }} {% if w.plik.url is not None %}<img src="{{ w.plik.url }}"  />{% endif %} </li>
  {% endfor %}
</ul>
<a href="{% url 'ankieter:create4' pytanie.id %}"> + Wybor </a>

{% endblock %}

ankietka/ankieter/templates/ankieter/wyniki.html
{% extends 'podstawa.html' %}

{% block content %}

<p>Wyniki ankiety {{ ankieta.nazwa_ankiety }} </p>

{% for grupa in ankieta.grupa_set.all %}
  <li> {{ grupa.nazwa_grupy }} </li>

  <ul>
    {% for pytanie in grupa.pytanie_set.all %}

<p>{{ pytanie.pytanie_text }}</p>

{% if pytanie.pytanie_plik.url is not None %}
<img src="{{ pytanie.pytanie_plik.url }}"  width="15%" height="15%"/>
{% endif %}


<p>Ankietowani odpowiedzieli:</p>
<ol>
{% for wybor in pytanie.wybor_set.all %}
    <li>{{ wybor.wybor_text }} {% if wybor.plik.url is not None %}<img src="{{ wybor.plik.url }}"  />{% endif %} : {{ wybor.votes }}</li>
{% endfor %}
</ol>

{% endfor %}
  </ul>


{% endfor %}

{% endblock%}